labels:
  bug:
    color: ee0701
  difficulty/newcomers:
    color: c5def5
  difficulty/easy:
    color: c2e0c6
  difficulty/hard:
    color: e99695
  difficulty/medium:
    color: fef2c0
  documentation:
    color: 1d76db
  etc/blocked:
    color: b60205
  etc/duplicate:
    color: cccccc
  etc/invalid:
    color: cccccc
  etc/question:
    color: cccccc
  etc/wontfix:
    color: cccccc
  feature/request:
    color: d93f0b
  feature/approved:
    color: 5319e7
  help wanted:
    color: 128A0C
  question:
    color: cc317c
options:
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_squash_merge: true
  description: Python (a)sync Slack API library
  has_downloads: true
  has_issues: true
  has_wiki: false
  homepage: ''
  name: slack-sansio
  private: false
